import React from "react";

function Card() {
  return (
    <div className="dark:bg-slate-950 dark:text-white py-5 px-4 md:px-10 lg:px-20 justify-center">
      <>
        <h2 className="dark:bg-slate-950 dark:text-white text-3xl font-bold text-center">
          Sample Books Generated by AI
        </h2>
        <br></br>
        <div className="justify-center py-10 pb-20">
          {/* Grid layout for responsive design */}
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-10">
            {/* Card 1 */}
            <div className="mx-auto">
              <div className="card bg-purple-950 text-slate-50 w-full max-w-xs shadow-xl hover:scale-105 duration-200">
                <figure className="px-10 pt-10">
                  <img src="bookai.png" alt="Book" className="rounded-xl" />
                </figure>
                <div className="card-body items-center text-center">
                  <h2 className="card-title">Mystery</h2>
                  <p>
                    "As Dr. Elara stepped through the shimmering portal, she
                    knew there was no turning back. The fate of two universes
                    now rested in her hands..."
                  </p>
                  <div className="card-actions">
                    <button className="btn btn-primary">Read More</button>
                  </div>
                </div>
              </div>
            </div>

            {/* Card 2 */}
            <div className="mx-auto">
              <div className="card bg-purple-950 text-slate-50 w-full max-w-xs shadow-xl hover:scale-105 duration-200">
                <figure className="px-10 pt-10">
                  <img src="bookai.png" alt="Book" className="rounded-xl" />
                </figure>
                <div className="card-body items-center text-center">
                  <h2 className="card-title">Science Fiction</h2>
                  <p>
                    "As Dr. Elara stepped through the shimmering portal, she
                    knew there was no turning back. The fate of two universes
                    now rested in her hands..."
                  </p>
                  <div className="card-actions">
                    <button className="btn btn-primary">Read More</button>
                  </div>
                </div>
              </div>
            </div>

            {/* Card 3 */}
            <div className="mx-auto">
              <div className="card bg-purple-950 text-slate-50 w-full max-w-xs shadow-xl hover:scale-105 duration-200">
                <figure className="px-10 pt-10">
                  <img src="bookai.png" alt="Book" className="rounded-xl" />
                </figure>
                <div className="card-body items-center text-center">
                  <h2 className="card-title">Fantasy</h2>
                  <p>
                    "As Dr. Elara stepped through the shimmering portal, she
                    knew there was no turning back. The fate of two universes
                    now rested in her hands..."
                  </p>
                  <div className="card-actions">
                    <button className="btn btn-primary">Read More</button>
                  </div>
                </div>
              </div>
            </div>

            {/* Card 4 */}
            <div className="mx-auto">
              <div className="card bg-purple-950 text-slate-50 w-full max-w-xs shadow-xl hover:scale-105 duration-200">
                <figure className="px-10 pt-10">
                  <img src="bookai.png" alt="Book" className="rounded-xl" />
                </figure>
                <div className="card-body items-center text-center">
                  <h2 className="card-title">Fantasy</h2>
                  <p>
                    "As Dr. Elara stepped through the shimmering portal, she
                    knew there was no turning back. The fate of two universes
                    now rested in her hands..."
                  </p>
                  <div className="card-actions">
                    <button className="btn btn-primary">Read More</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </>
    </div>
  );
}

export default Card;
